//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserMgmt.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using UserMgmt.Validation;

    public partial class User
    {
        [DisplayName("Id")]
        public int Id { get; set; }

        [Required]
        [DisplayName("First Name")]
        [DataType(DataType.Text)]
        [RegularExpression(@"^[A-Z][a-zA-Z]*$", ErrorMessage = "Enter valid name, Eg: Sam")]
        public string FirstName { get; set; }

        [Required]
        [DisplayName("Last Name")]
        [DataType(DataType.Text)]
        [RegularExpression(@"^[A-Z][a-zA-Z]*$", ErrorMessage = "Enter valid name, eg: Brown")]
        public string LastName { get; set; }

        [Required]
        [DisplayName("Email")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [DisplayName("Mobile")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^(\+44\s?7\d{3}|\(?07\d{3}\)?)\s?\d{3}\s?\d{3}$", ErrorMessage = "Enter valid phone number")]
        public string Mobile { get; set; }

        [DisplayName("Date of Birth")]
        [DataType(DataType.Date)]
        [ValidateDate(MinAge = 0, MaxAge = 150)]
        public System.DateTime BirthDate { get; set; }

        [DisplayName("Modified Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public System.DateTime ModifyDate { get; set; }
    }
}
